name: CI

on: push

jobs:
  # Confirm the coverity upload
  coverity_upload:
    uses: teragrep/rl0_08/.github/workflows/coverity_upload.yaml@bease-feat
    secrets: 
      COVERITY_TOKEN: ${{ secrets.COVERITY_TOKEN }}
      COVERITY_EMAIL: ${{ secrets.COVERITY_EMAIL }}
  
